/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.panamahitek.PanamaHitek_Arduino;
import controlador.CrearXml;
import controlador.GuardarSqlite;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.net.SocketException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.BillCassette;
import modelo.Ticket;

/**
 *
 * @author vbarrera
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    final String HOST = "10.43.1.97";
    final int PUERTO = 10001;
    Socket conector;
    BufferedReader entrada;
    DataOutputStream salida;
    Thread hilo;
    Thread hilo1;
    BillCassette cassette = new BillCassette();
    Ticket ticket = new Ticket();
    GuardarSqlite sqlite = new GuardarSqlite();
    DefaultTableModel m;
    final double B2K = 2000.00;
    final double B5K = 5000.00;
    final double B10K = 10000.00;
    final double B20K = 20000.00;
    final double B50K = 50000.00;
    final double B100K = 100000.00;
    PanamaHitek_Arduino puertoCom = new PanamaHitek_Arduino();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    SimpleDateFormat sdfSqlite = new SimpleDateFormat("yyyy-MM-dd");
    SerialPortEventListener event = new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent spe) {
            // String dato = null;
            boolean estado = false;
            if (puertoCom.isMessageAvailable()) {
                String dato = puertoCom.printMessage();

                for (int i = 0; i < tablaTikect.getRowCount(); i++) {
                    System.out.println("T" + tablaTikect.getValueAt(i, 0));
                    if (dato.equals(tablaTikect.getValueAt(i, 0))) {
                        estado = true;
                    }
                }
                if (!sqlite.consultarTicket(dato) && !estado) {

                    System.err.println("d " + sqlite.consultarTicket(dato));
                    IngresarTikect(dato);
                }

            }
        }
    };

    public Inicio() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        PrepararTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botoInicioConteo = new javax.swing.JButton();
        textNumerosMaquina = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        textValor10k = new javax.swing.JTextField();
        textValor20k = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textValor50k = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textUnid100k = new javax.swing.JTextField();
        textUnid50k = new javax.swing.JTextField();
        textUnid20k = new javax.swing.JTextField();
        textUnid10k = new javax.swing.JTextField();
        textUnid5k = new javax.swing.JTextField();
        textUnid2k = new javax.swing.JTextField();
        textValor100k = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textValor2k = new javax.swing.JTextField();
        textValor5k = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textValorTotal = new javax.swing.JTextField();
        textUnidTotal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTikect = new javax.swing.JTable();
        botonIngresoTicket = new javax.swing.JButton();
        botonEliminarTicket = new javax.swing.JButton();
        botonFinLote = new javax.swing.JButton();
        textTikect = new javax.swing.JTextField();
        botonReporte = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        etiTotalTicket = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();
        dateFecha = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conteo ");

        botoInicioConteo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botoInicioConteo.setText("INICIO");
        botoInicioConteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoInicioConteoActionPerformed(evt);
            }
        });

        textNumerosMaquina.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textNumerosMaquina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNumerosMaquina.setEnabled(false);

        textValor10k.setEditable(false);
        textValor10k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textValor10k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValor10k.setText("0");

        textValor20k.setEditable(false);
        textValor20k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textValor20k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValor20k.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("COP 100000");

        textValor50k.setEditable(false);
        textValor50k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textValor50k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValor50k.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("COP 2000");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("COP 5000");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("COP 10000");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("VALOR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("COP 20000");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("COP 50000");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("COP");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("COP");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("DENOMINACIÓN ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("COP");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("COP");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("COP");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("COP");

        textUnid100k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUnid100k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textUnid100k.setText("0");

        textUnid50k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUnid50k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textUnid50k.setText("0");

        textUnid20k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUnid20k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textUnid20k.setText("0");

        textUnid10k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUnid10k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textUnid10k.setText("0");

        textUnid5k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUnid5k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textUnid5k.setText("0");

        textUnid2k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUnid2k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textUnid2k.setText("0");

        textValor100k.setEditable(false);
        textValor100k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textValor100k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValor100k.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("UNID");

        textValor2k.setEditable(false);
        textValor2k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textValor2k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValor2k.setText("0");

        textValor5k.setEditable(false);
        textValor5k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textValor5k.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValor5k.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("TOTAL");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("COP");

        textValorTotal.setEditable(false);
        textValorTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textValorTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValorTotal.setText("0");

        textUnidTotal.setEditable(false);
        textUnidTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textUnidTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textUnidTotal.setText("0");

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("TICKET");

        tablaTikect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tikect"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTikect.setAutoscrolls(false);
        tablaTikect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tablaTikect);
        if (tablaTikect.getColumnModel().getColumnCount() > 0) {
            tablaTikect.getColumnModel().getColumn(0).setMaxWidth(500);
        }

        botonIngresoTicket.setText("INGRESAR TICKET");
        botonIngresoTicket.setEnabled(false);
        botonIngresoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoTicketActionPerformed(evt);
            }
        });

        botonEliminarTicket.setText("ELIMINAR TICKET");
        botonEliminarTicket.setEnabled(false);
        botonEliminarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTicketActionPerformed(evt);
            }
        });

        botonFinLote.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonFinLote.setText("FIN DE LOTE");
        botonFinLote.setEnabled(false);
        botonFinLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinLoteActionPerformed(evt);
            }
        });

        textTikect.setEnabled(false);

        botonReporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonReporte.setText("REPORTE");
        botonReporte.setEnabled(false);
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("TICKET");

        etiTotalTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiTotalTicket.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(102, 102, 102)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(138, 138, 138))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(textValor100k, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textUnidTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(54, 54, 54)
                                            .addComponent(jLabel10))
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textValor20k, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textValor50k, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textValor2k, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textValor5k, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textValor10k, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textUnid20k, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textUnid50k, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textUnid10k, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textUnid2k, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textUnid5k, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(textUnid100k, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textTikect, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonIngresoTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonEliminarTicket)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(etiTotalTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(botonFinLote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonReporte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textValor2k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textValor5k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textValor10k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textValor20k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textValor50k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textUnid2k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textUnid5k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(textUnid10k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textUnid20k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textUnid50k, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textUnid100k, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textValor100k, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textUnidTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTikect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(etiTotalTicket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonIngresoTicket)
                            .addComponent(botonEliminarTicket))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFinLote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        botonBorrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonBorrar.setText("BORRAR");
        botonBorrar.setEnabled(false);
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        dateFecha.setEnabled(false);
        dateFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateFecha.setMinSelectableDate(new java.util.Date(-62135747884000L));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("FECHA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botoInicioConteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNumerosMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botoInicioConteo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNumerosMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean buscarTicket() {
        boolean estado = false;
        for (int i = 0; i < tablaTikect.getRowCount(); i++) {
            System.out.println("T" + tablaTikect.getValueAt(i, 0));
            estado = true;
        }
        return estado;
    }

    public boolean conectar() {
        try {
            conector = new Socket(HOST, PUERTO);
            System.out.println("Conectado a " + conector.getInetAddress().getHostAddress());
            hilo = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        String dato;
                        entrada = new BufferedReader(new InputStreamReader(conector.getInputStream()));
                        int unidadBill = 0;
                        int valorBill = 0;
                        String denomBill = null;
                        int uni2k = 0;
                        int uni5k = 0;
                        int uni10k = 0;
                        int uni20k = 0;
                        int uni50k = 0;
                        int uni100k = 0;
                        while ((dato = entrada.readLine()) != null) {
                            if (!dato.isEmpty()) {
                                
                                if (dato.contains("COP2K")) {
                                    uni2k = Integer.parseInt(dato.substring(14, 20).trim());
                                    cassette.setBill2k(uni2k);
                                    textUnid2k.setText(cassette.getBill2k() + "");
                                    textValor2k.setText("" + (cassette.getBill2k() * B2K));
                                }
                                if (dato.contains("COP5K")) {
                                    uni5k = Integer.parseInt(dato.substring(14, 20).trim());
                                    cassette.setBill5k(uni5k);
                                    textUnid5k.setText(cassette.getBill5k() + "");
                                    textValor5k.setText("" + (cassette.getBill5k() * B5K));
                                }
                                if (dato.contains("COP10K")) {
                                    uni10k = Integer.parseInt(dato.substring(14, 20).trim());
                                    cassette.setBill10k(uni10k);
                                    textUnid10k.setText(cassette.getBill10k() + "");
                                    textValor10k.setText("" + (cassette.getBill10k() * B10K));
                                }
                                if (dato.contains("COP20K")) {
                                    uni20k = Integer.parseInt(dato.substring(14, 21).trim());
                                    cassette.setBill20k(uni20k);
                                    textUnid20k.setText(cassette.getBill20k() + "");
                                    textValor20k.setText("" + (cassette.getBill20k() * B20K));
                                }
                                if (dato.contains("COP50K")) {
                                    uni50k = Integer.parseInt(dato.substring(14, 20).trim());
                                    cassette.setBill50k(uni50k);
                                    textUnid50k.setText(cassette.getBill50k() + "");
                                    textValor50k.setText("" + (cassette.getBill50k() * B50K));
                                }
                                if (dato.contains("COP100K")) {
                                    uni100k = Integer.parseInt(dato.substring(14, 20).trim());
                                    cassette.setBill100k(uni100k);
                                    textUnid100k.setText(cassette.getBill100k() + "");
                                    textValor100k.setText("" + (cassette.getBill100k() * B100K));
                                }
                                if (dato.contains("LOTE") && dato.length() > 34) {
                                    unidadBill = Integer.parseInt(dato.substring(14, 20).trim());
                                    valorBill = Integer.parseInt(dato.substring(28, 35).trim().replace("K", "000"));
                                    //System.out.println(""+unidadBill+" "+valorBill);

                                    textUnidTotal.setText("" + unidadBill);
                                    textValorTotal.setText("" + valorBill);
                                    cassette.setTotalUnidad(Integer.parseInt(textUnidTotal.getText()));
                                    cassette.setTotalValor(Integer.parseInt(textValorTotal.getText()));
                                }
                            }/*
                             textUnid1k.setText(cassette.getBill1k() + "");
                             textValor1k.setText("" + (cassette.getBill1k() * B1K));
                             textUnid2k.setText(cassette.getBill2k() + "");
                             textValor2k.setText("" + (cassette.getBill2k() * B2K));
                             textUnid5k.setText(cassette.getBill5k() + "");
                             textValor5k.setText("" + (cassette.getBill5k() * B5K));
                             textUnid10k.setText(cassette.getBill10k() + "");
                             textValor10k.setText("" + (cassette.getBill10k() * B10K));
                             textUnid20k.setText(cassette.getBill20k() + "");
                             textValor20k.setText("" + (cassette.getBill20k() * B20K));
                             textUnid50k.setText(cassette.getBill50k() + "");
                             textValor50k.setText("" + (cassette.getBill50k() * B50K));
                             textUnidTotal.setText("" + cassette.getTotalUnidad());
                             textValorTotal.setText("" + cassette.getTotalValor());*/

                            // recibido.append(dato + "\n"); 

                        }
                    } catch (SocketException ex) {
                        try {
                            System.out.println("1 " + ex.getMessage());
                            System.out.println("Desconectado a " + conector.getInetAddress().getHostAddress());
                            JOptionPane.showMessageDialog(null, "Cummins Desconectado o Apagado");
                            hilo.stop();
                            salida.close();
                            entrada.close();
                            conector.close();
                        } catch (IOException ex1) {
                            System.out.println("6 " + ex1.getMessage());
                        }
                    } catch (IOException ex) {
                        System.out.println("2 " + ex.getMessage());
                    } catch (Exception ex) {
                        System.out.println("3 " + ex.getMessage());
                    }
                }
            }
            );
            hilo.start();
        } catch (SocketException ex) {
            System.out.println("4 " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Cummins Desconectado o Apagado");
            return false;
        } catch (IOException ex) {
            System.out.println("5 " + ex.getMessage());
        }
        return true;

    }
    private void botoInicioConteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoInicioConteoActionPerformed
        /*if (!conectar()) {
            System.exit(0);
        }*/
        //System.out.println(sdf.format(dateFecha.getDate()).replace(" ", "T"));
        botoInicioConteo.setEnabled(false);
        textNumerosMaquina.setEnabled(true);
        dateFecha.setEnabled(true);
        try {
          //  puertoCom.arduinoRX("COM1", 9600, event);
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);

            System.exit(0);

        }
        hilo1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {

                }
            }
        });
        //hilo1.start();
        botonFinLote.setEnabled(true);
        botonReporte.setEnabled(true);
        textTikect.setEnabled(true);
        botonIngresoTicket.setEnabled(true);
        botonEliminarTicket.setEnabled(true);
        botonBorrar.setEnabled(true);
    }//GEN-LAST:event_botoInicioConteoActionPerformed

    public void PrepararTabla() {
        String titulos[] = {"Ticket"};
        m = new DefaultTableModel(null, titulos);
        if (tablaTikect.getColumnModel().getColumnCount() > 0) {
            tablaTikect.getColumnModel().getColumn(0).setMaxWidth(500);
        }
        tablaTikect.setModel(m);
        if (tablaTikect.getColumnModel().getColumnCount() > 0) {
            tablaTikect.getColumnModel().getColumn(0).setMinWidth(1);
            tablaTikect.getColumnModel().getColumn(0).setMaxWidth(200);
        }
    }

    public void IngresarTikect(String tikect) {
        m = (DefaultTableModel) tablaTikect.getModel();
        String filaElemento[] = {tikect};
        m.addRow(filaElemento);
        textTikect.setText("");
        etiTotalTicket.setText("" + m.getRowCount());
    }

    public void BorrarDenominador() {
        /*cassette.setBill1k(0);
         cassette.setBill2k(0);
         cassette.setBill5k(0);
         cassette.setBill10k(0);
         cassette.setBill20k(0);
         cassette.setBill50k(0);
         cassette.setTotalUnidad(0);
         cassette.setTotalValor(0);
         //*/
        textUnid100k.setText("0");
        textUnid2k.setText("0");
        textUnid5k.setText("0");
        textUnid10k.setText("0");
        textUnid20k.setText("0");
        textUnid50k.setText("0");
        textValorTotal.setText("0");
        textUnidTotal.setText("0");
        textValor100k.setText("0");
        textValor2k.setText("0");
        textValor5k.setText("0");
        textValor10k.setText("0");
        textValor20k.setText("0");
        textValor50k.setText("0");
        textNumerosMaquina.setText(null);
    }
    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        BorrarDenominador();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonIngresoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoTicketActionPerformed
        /*try {
         long Numeros = Long.valueOf(textTikect.getText());
         } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(null, "Solo Numeros En EL Campo De Ticket");
         textTikect.setText("");
         return;
         }*/
        IngresarTikect(textTikect.getText());

    }//GEN-LAST:event_botonIngresoTicketActionPerformed

    private void botonEliminarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTicketActionPerformed
        /*
         for (int i = 0; i < tablaTikect.getRowCount(); i++) {
         m.removeRow(i);
         i -= 1;
         textTikect.setText("");
         etiTotalTicket.setText("" + m.getRowCount());
         }*/
        int filasel = tablaTikect.getSelectedRow();
        if (filasel == -1) {
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada");
        } else {
            m = (DefaultTableModel) tablaTikect.getModel();
            m.removeRow(filasel);

        }
        etiTotalTicket.setText("" + m.getRowCount());

    }//GEN-LAST:event_botonEliminarTicketActionPerformed

    private void botonFinLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinLoteActionPerformed
        if (sqlite.consultarMaquina(Integer.parseInt(textNumerosMaquina.getText()), sdfSqlite.format(dateFecha.getDate()))) {
            JOptionPane.showMessageDialog(null, "Maquina Registrada el dia de hoy");
            return;
        }
        botonFinLote.setEnabled(false);
        if (textNumerosMaquina.getText().length() != 5) {
            botonFinLote.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Numero de  Maquina Errado");
            return;
        } else if (dateFecha.getDate() == null) {
            botonFinLote.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ingresar dia del conteo");
            return;
        }

        try {
            long Numeros = Long.valueOf(textNumerosMaquina.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Solo Numeros En El Campos De Maquina");
            botonFinLote.setEnabled(true);
            return;
        }
        cassette.setSlotNumber(Integer.parseInt(textNumerosMaquina.getText()));
        cassette.setDate(sdfSqlite.format(dateFecha.getDate()));

        sqlite.guardarBill(cassette, "" + textUnid100k.getText(), "" + textUnid2k.getText(), textUnid5k.getText(), textUnid10k.getText(), textUnid20k.getText(), textUnid50k.getText());
        System.err.println("" + textUnid100k.getText() + " " + textUnid2k.getText() + " " + textUnid5k.getText() + " " + textUnid10k.getText() + " " + textUnid20k.getText() + " " + textUnid50k.getText());
        cassette.setTotalUnidad(0);
        cassette.setTotalValor(0);
        if (tablaTikect.getRowCount() >= 1) {
            ticket.setSlotNumber(Integer.parseInt(textNumerosMaquina.getText()));
            ticket.setDate(sdfSqlite.format(dateFecha.getDate()));
            //DefaultTableModel m = (DefaultTableModel) tablaTikect.getModel();

            for (int i = 0; i < tablaTikect.getRowCount(); i++) {
                ticket.setTicket((String) tablaTikect.getValueAt(i, 0));
                sqlite.guardarTicket(ticket);
                m.removeRow(i);
                i -= 1;
                textTikect.setText("");
                etiTotalTicket.setText("" + m.getRowCount());
            }
        }
        botonFinLote.setEnabled(true);
        // textNumerosMaquina.setText(null);
        BorrarDenominador();

//        try {
//            puertoCom.killArduinoConnection();
//        } catch (Exception ex) {
//            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        hilo1.stop();
    }//GEN-LAST:event_botonFinLoteActionPerformed

    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
        if (dateFecha.getDate() == null) {
            botonFinLote.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ingresar dia del conteo");
            return;
        } else {
            CrearXml crearXml = new CrearXml();
            crearXml.generarXml(sdfSqlite.format(dateFecha.getDate()));
            JOptionPane.showMessageDialog(null, "Reporte Generado Exitosamente");
            //tablaTikect.getValueAt(B1K, 0)

        }

    }//GEN-LAST:event_botonReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoInicioConteo;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonEliminarTicket;
    private javax.swing.JButton botonFinLote;
    private javax.swing.JButton botonIngresoTicket;
    private javax.swing.JButton botonReporte;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel etiTotalTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaTikect;
    private javax.swing.JTextField textNumerosMaquina;
    private javax.swing.JTextField textTikect;
    private javax.swing.JTextField textUnid100k;
    private javax.swing.JTextField textUnid10k;
    private javax.swing.JTextField textUnid20k;
    private javax.swing.JTextField textUnid2k;
    private javax.swing.JTextField textUnid50k;
    private javax.swing.JTextField textUnid5k;
    private javax.swing.JTextField textUnidTotal;
    private javax.swing.JTextField textValor100k;
    private javax.swing.JTextField textValor10k;
    private javax.swing.JTextField textValor20k;
    private javax.swing.JTextField textValor2k;
    private javax.swing.JTextField textValor50k;
    private javax.swing.JTextField textValor5k;
    private javax.swing.JTextField textValorTotal;
    // End of variables declaration//GEN-END:variables
}
